# Generated by Django 3.2.16 on 2023-08-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_post_comment_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object',
            new_name='blog_post',
        ),
    ]
